# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5681b7000eba4bb09f2cc4b99dbefeb1c2afe66c377607d4b65f5f9d1284393ae95ff93c946b2279205b8e702be6aab5895c5cf6d9c825e816ceddce8eb4aa5d

test:
  secret_key_base: 9e0193b8798120dd2ee7fdd8f2e4be011c7007c3c63c59f04970f86c0e25df3545f5b1c6de549d4477b83cdaf291787f6a5075876391fc2917000fa810dd8a44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
